name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - "#11"

jobs:
  cd:
    name: Deploy to prod
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: web-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            web-${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build production
        run: CI=false npm run build
        env:
          NODE_ENV: production
# temporary hack until consolidated secrets management...
          REACT_APP_JIRA_FEEDBACK_URI: ${{ secrets.JIRA_FEEDBACK_URI }}
          REACT_APP_STRIPE_STARTER_TIER_PRICE_ID: ${{ secrets.STRIPE_STARTER_TIER_PRICE_ID }}
          REACT_APP_STRIPE_PRO_TIER_PRICE_ID: ${{ secrets.STRIPE_PRO_TIER_PRICE_ID }}
          REACT_APP_STRIPE_TEST_API_TOKEN: ${{ secrets.STRIPE_TEST_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_CD_IAM_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_CD_IAM_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files to prod
        run: |
          aws s3 cp ./ s3://offcmpus.io/ --recursive
        working-directory: build
